@startuml

class Contact {
    String name
    String phoneNumber
    Contact(String name, String phoneNumber)
    String getName()
    String getPhoneNumber()
}
class BusinessContact extends Contact {
    String company
    BusinessContact(String name, String phoneNumber, String company)
    String getCompany()
}
class PersonalContact extends Contact {
    String relationship
    PersonalContact(String name, String phoneNumber, String relationship)
    String getRelationship()
}
class AddressBook {
    List<Contact> contacts
    AddressBook()
    void addContact(Contact contact)
    void displayContacts()
    void searchContact(String name)
    void main(String[] args)
}

@enduml